language: ruby
before_script:
  - "sudo aptitude -y -q install libx264-dev libvpx-dev libfaac-dev yasm"
  - "sudo ci/install_ffmpeg"
  - "export PATH=ffmpeg/bin:$PATH"
  - "ffmpeg -version"
script: "bundle exec rspec spec"
rvm:
  - 2.0.0
  - 1.9.3
