language: ruby
before_install:
  - sudo apt-get update
  - sudo apt-get -y install libx264-dev libvpx-dev libfaac-dev libvorbis-dev yasm
before_script:
  - "sudo ci/install_ffmpeg"
  - ls
  - "export PATH=ffmpeg/bin:$PATH"
  - "ffmpeg -version"
script: "bundle exec rspec spec"
rvm:
  - 2.0.0
  - 1.9.3
env:
  - FFMPEG_VERSION=1.1.3
  - FFMPEG_VERSION=1.0.5
